[scripts]

[scripts.oncreate]
[scripts.oncreate.universal]
init_git = ["git init"]

[scripts.onmount]
[scripts.onmount.universal]
init_package = [
    "go mod init {{ .ModuleName }}",
    "go mod tidy"
]
